using SalesInventory.businesslogic;
using SalesInventory.BusinessLogic;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using SalesInventory.Repository;

namespace SalesInventory.ui
{
    public partial class AdminProductMaintenanceForm : Form
    {
        private readonly ProductService productService;
        private int selectedProductID = 0;

        public AdminProductMaintenanceForm()
        {
            InitializeComponent();

            productService = new ProductService();

            // Configure controls
            ConfigureControls();

            // Load data
            LoadCategories();
            LoadSuppliers();
            LoadProducts();

            // Events
            btnAdd.Click += btnAdd_Click;
            btnUpdate.Click += btnUpdate_Click;
            btnDelete.Click += btnDelete_Click;
            btnClear.Click += btnClear_Click;
            button11.Click += button11_Click;
            dgvProducts.CellClick += dgvProducts_CellClick;

            btnDashboard.Click += btnDashboard_Click;
            btnCategories.Click += btnCategories_Click;
            btnSuppliers.Click += btnSuppliers_Click;
            btnProducts.Click += btnProducts_Click;
            btnLogout.Click += btnLogout_Click;
        }

        private void LoadProducts()
        {
            try
            {
                dgvProducts.DataSource = null;
                dgvProducts.DataSource = productService.GetAllProducts();

                dgvProducts.ClearSelection();

                // Optional display settings
                if (dgvProducts.Columns["ProductID"] != null)
                    dgvProducts.Columns["ProductID"].HeaderText = "Product ID";

                if (dgvProducts.Columns["ProductName"] != null)
                    dgvProducts.Columns["ProductName"].HeaderText = "Product Name";

                if (dgvProducts.Columns["CategoryID"] != null)
                    dgvProducts.Columns["CategoryID"].HeaderText = "Category ID";

                if (dgvProducts.Columns["SupplierID"] != null)
                    dgvProducts.Columns["SupplierID"].HeaderText = "Supplier ID";

                if (dgvProducts.Columns["UnitPrice"] != null)
                    dgvProducts.Columns["UnitPrice"].HeaderText = "Unit Price";

                if (dgvProducts.Columns["InitialStock"] != null)
                    dgvProducts.Columns["InitialStock"].HeaderText = "Initial Stock";

                if (dgvProducts.Columns["ReorderLevel"] != null)
                    dgvProducts.Columns["ReorderLevel"].HeaderText = "Reorder Level";

                if (dgvProducts.Columns["Status"] != null)
                    dgvProducts.Columns["Status"].HeaderText = "Status";
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    "Error loading products:\n" + ex.Message,
                    "Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
            }
        }
        private void LoadCategories()
        {
            try
            {
                CategoryRepository repository = new CategoryRepository();

                comboBox1.DataSource = null;
                comboBox1.DataSource = repository.GetAllCategories();

                comboBox1.DisplayMember = "CategoryName";
                comboBox1.ValueMember = "CategoryID";

                comboBox1.SelectedIndex = -1;
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    "Error loading categories:\n" + ex.Message,
                    "Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
            }
        }

        private void LoadSuppliers()
        {
            try
            {
                SupplierRepository repository = new SupplierRepository();

                comboBox3.DataSource = null;
                comboBox3.DataSource = repository.GetAllSuppliers();

                comboBox3.DisplayMember = "SupplierName";
                comboBox3.ValueMember = "SupplierID";

                comboBox3.SelectedIndex = -1;
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    "Error loading suppliers:\n" + ex.Message,
                    "Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
            }
        }
        private void ConfigureControls()
        {
            // Product ID is generated by database
            textBox2.ReadOnly = true;

            // Status
            comboBox2.Items.Clear();
            comboBox2.Items.Add("Active");
            comboBox2.Items.Add("Inactive");
            comboBox2.SelectedIndex = 0;

            // Numeric fields cannot go below zero
            numericUpDown1.Minimum = 0;
            numericUpDown2.Minimum = 0;
            numericUpDown3.Minimum = 0;

            // Unit Price
            numericUpDown1.DecimalPlaces = 2;
            numericUpDown1.Maximum = 999999999;

            // Stock
            numericUpDown2.Maximum = 999999999;

            // Reorder Level
            numericUpDown3.Maximum = 999999999;
        }



        private void AdminProductMaintenanceForm_Load(object sender, EventArgs e)
        {

        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(textBox1.Text))
                {
                    MessageBox.Show(
                        "Product name is required.",
                        "Validation",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning);

                    textBox1.Focus();
                    return;
                }

                if (comboBox1.SelectedIndex == -1)
                {
                    MessageBox.Show(
                        "Please select a category.",
                        "Validation",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning);

                    comboBox1.Focus();
                    return;
                }

                if (comboBox3.SelectedIndex == -1)
                {
                    MessageBox.Show(
                        "Please select a supplier.",
                        "Validation",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning);

                    comboBox3.Focus();
                    return;
                }

                Product product = new Product
                {
                    ProductName = textBox1.Text.Trim(),
                    CategoryID = Convert.ToInt32(comboBox1.SelectedValue),
                    SupplierID = Convert.ToInt32(comboBox3.SelectedValue),
                    UnitPrice = numericUpDown1.Value,
                    InitialStock = Convert.ToInt32(numericUpDown2.Value),
                    ReorderLevel = Convert.ToInt32(numericUpDown3.Value),
                    Status = comboBox2.Text
                };

                productService.AddProduct(product);

                MessageBox.Show(
                    "Product added successfully!",
                    "Success",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information);

                LoadProducts();
                ClearFields();
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    "Error adding product:\n" + ex.Message,
                    "Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
            }
        }

        private void btnUpdate_Click(object sender, EventArgs e)
        {
            try
            {
                if (selectedProductID == 0)
                {
                    MessageBox.Show(
                        "Please select a product from the table first.",
                        "Update Product",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning);

                    return;
                }

                if (string.IsNullOrWhiteSpace(textBox1.Text))
                {
                    MessageBox.Show(
                        "Product name is required.",
                        "Validation",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning);

                    textBox1.Focus();
                    return;
                }

                if (comboBox1.SelectedIndex == -1)
                {
                    MessageBox.Show(
                        "Please select a category.",
                        "Validation",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning);

                    return;
                }

                if (comboBox3.SelectedIndex == -1)
                {
                    MessageBox.Show(
                        "Please select a supplier.",
                        "Validation",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning);

                    return;
                }

                Product product = new Product
                {
                    ProductID = selectedProductID,
                    ProductName = textBox1.Text.Trim(),
                    CategoryID = Convert.ToInt32(comboBox1.SelectedValue),
                    SupplierID = Convert.ToInt32(comboBox3.SelectedValue),
                    UnitPrice = numericUpDown1.Value,
                    InitialStock = Convert.ToInt32(numericUpDown2.Value),
                    ReorderLevel = Convert.ToInt32(numericUpDown3.Value),
                    Status = comboBox2.Text
                };

                productService.UpdateProduct(product);

                MessageBox.Show(
                    "Product updated successfully!",
                    "Success",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information);

                LoadProducts();
                ClearFields();
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    "Error updating product:\n" + ex.Message,
                    "Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
            }
        }

        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                if (selectedProductID == 0)
                {
                    MessageBox.Show(
                        "Please select a product first.",
                        "Deactivate Product",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning);

                    return;
                }

                DialogResult result = MessageBox.Show(
                    "Are you sure you want to deactivate this product?",
                    "Confirm Deactivation",
                    MessageBoxButtons.YesNo,
                    MessageBoxIcon.Question);

                if (result != DialogResult.Yes)
                    return;

                productService.DeactivateProduct(selectedProductID);

                MessageBox.Show(
                    "Product deactivated successfully!",
                    "Success",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information);

                LoadProducts();
                ClearFields();
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    "Error deactivating product:\n" + ex.Message,
                    "Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
            }
        }

        private void button11_Click(object sender, EventArgs e)
        {
            try
            {
                string keyword = txtSearchProduct.Text.Trim();

                if (string.IsNullOrWhiteSpace(keyword))
                {
                    LoadProducts();
                    return;
                }

                var results = productService.SearchProducts(keyword);

                dgvProducts.DataSource = null;
                dgvProducts.DataSource = results;

                if (results.Count == 0)
                {
                    MessageBox.Show(
                        "No product found.",
                        "Search",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Information);
                }

                dgvProducts.ClearSelection();
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    "Error searching products:\n" + ex.Message,
                    "Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
            }
        }

        private void dataGridView1_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            try
            {
                if (e.RowIndex < 0)
                    return;

                DataGridViewRow row = dgvProducts.Rows[e.RowIndex];

                if (row.Cells["ProductID"].Value == null)
                    return;

                selectedProductID =
                    Convert.ToInt32(row.Cells["ProductID"].Value);

                textBox2.Text = selectedProductID.ToString();

                textBox1.Text =
                    row.Cells["ProductName"].Value?.ToString() ?? "";

                numericUpDown1.Value =
                    Convert.ToDecimal(row.Cells["UnitPrice"].Value);

                numericUpDown2.Value =
                    Convert.ToDecimal(row.Cells["InitialStock"].Value);

                numericUpDown3.Value =
                    Convert.ToDecimal(row.Cells["ReorderLevel"].Value);

                string status =
                    row.Cells["Status"].Value?.ToString() ?? "Active";

                if (comboBox2.Items.Contains(status))
                    comboBox2.SelectedItem = status;

                // Select Category
                if (row.Cells["CategoryID"].Value != null)
                {
                    int categoryID =
                        Convert.ToInt32(row.Cells["CategoryID"].Value);

                    comboBox1.SelectedValue = categoryID;
                }

                // Select Supplier
                if (row.Cells["SupplierID"].Value != null)
                {
                    int supplierID =
                        Convert.ToInt32(row.Cells["SupplierID"].Value);

                    comboBox3.SelectedValue = supplierID;
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    "Error selecting product:\n" + ex.Message,
                    "Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
            }
        }

        private void btnClear_Click(object sender, EventArgs e)
        {
            ClearFields();
        }

        private void ClearFields()
        {
            selectedProductID = 0;

            textBox2.Clear();
            textBox1.Clear();

            comboBox1.SelectedIndex = -1;
            comboBox3.SelectedIndex = -1;

            if (comboBox2.Items.Count > 0)
                comboBox2.SelectedIndex = 0;

            numericUpDown1.Value = 0;
            numericUpDown2.Value = 0;
            numericUpDown3.Value = 0;

            dgvProducts.ClearSelection();
        }

        private void btnDashboard_Click(object sender, EventArgs e)
        {
            AdminDashboard dashboard = new AdminDashboard();
            dashboard.Show();

            this.Close();
        }

        private void btnCategories_Click(object sender, EventArgs e)
        {
            AdminCategoryForm categoryForm =
                new AdminCategoryForm();

            categoryForm.Show();

            this.Close();
        }

        private void btnSuppliers_Click(object sender, EventArgs e)
        {
            AdminSupplierForm supplierForm =
              new AdminSupplierForm();

            supplierForm.Show();

            this.Close();
        }

        private void btnLogout_Click(object sender, EventArgs e)
        {
            DialogResult result = MessageBox.Show(
                "Are you sure you want to logout?",
                "Logout",
                MessageBoxButtons.YesNo,
                MessageBoxIcon.Question);

            if (result != DialogResult.Yes)
                return;

            LoginFrom loginForm =
                Application.OpenForms
                .OfType<LoginFrom>()
                .FirstOrDefault();

            if (loginForm != null)
            {
                loginForm.Show();
            }
            else
            {
                LoginFrom newLoginForm = new LoginFrom();
                newLoginForm.Show();
            }

            this.Close();
        }

        private void dgvProducts_CellClick(object sender, DataGridViewCellEventArgs e)
        {

        }

        private void btnProducts_Click(object sender, EventArgs e)
        {

        }
    }
}
    